language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - pypy

install:
    "pip install -r requirements.txt --use-mirrors"

script:
  - bin/whisper-create.py --help
  - bin/whisper-dump.py --help
  - bin/whisper-fetch.py --help
  - bin/whisper-info.py --help
  - bin/whisper-merge.py --help
  - bin/whisper-resize.py --help
  - bin/whisper-set-aggregation-method.py --help
  - bin/whisper-update.py --help
  - contrib/whisper-auto-update.py --help
  - contrib/whisper-auto-resize.py --help
  # Run the unit tests for >= 2.6, the test uses with statements
  - "if echo $TRAVIS_PYTHON_VERSION | egrep -q '^(2.6|pypy)$'; then pip install unittest2 --use-mirrors; fi"
  - "if echo $TRAVIS_PYTHON_VERSION | egrep -q '^(2.[67]|pypy)$'; then python test_whisper.py; fi"
