language: python

python:
  - 2.6
  - 2.7
  - pypy

install:
  - pip install .
  - pip install coverage coveralls

script:
  - bin/whisper-create.py --help
  - bin/whisper-dump.py --help
  - bin/whisper-estimate.py --help
  - bin/whisper-fetch.py --help
  - bin/whisper-info.py --help
  - bin/whisper-merge.py --help
  - bin/whisper-resize.py --help
  - bin/whisper-set-aggregation-method.py --help
  - bin/whisper-update.py --help
  - contrib/whisper-auto-update.py --help
  - contrib/whisper-auto-resize.py --help
  - "if echo $TRAVIS_PYTHON_VERSION | egrep -q '^(2.6|pypy)$'; then pip install unittest2 --use-mirrors; fi"
  # Coverage of tests ensures we don't have dead coded in the tests
  - coverage run --include='whisper.py,test_whisper.py' test_whisper.py
after_success:
  coveralls
